export {
  SESSION_DURATION_MS,
  AUTH_COOKIE_NAME,
  hashPassword,
  verifyPassword,
  signAuthToken,
  verifyAuthToken,
  type AuthTokenPayload,
  getTokenFromRequest,
  getTokenFromCookieHeader,
  buildAuthCookie,
  buildClearAuthCookie,
  setAuthCookieOnResponse,
  clearAuthCookieOnResponse,
  verifyAuthFromRequest,
  verifyAuthFromCookieHeader,
  requireAuth,
  requireRoomMember,
  isAuthError,
  type AuthenticatedUser,
  type RoomAuthenticatedUser,
} from "./auth/index"
